# ============================================================
# database.tf
# ============================================================
# This file handles everything data-layer:
#
#   1. Random password generation (never hardcode secrets)
#   2. SSM Parameter Store (secure secret storage)
#   3. RDS Subnet Group (tells RDS which subnets to use)
#   4. RDS MySQL Instance
#
# KEY SECURITY PRINCIPLE:
# The DB password is generated by Terraform, immediately
# stored encrypted in SSM, and never appears in any file.
# Your app reads it from SSM at runtime.
# ============================================================


# ============================================================
# 1. RANDOM PASSWORD
# ============================================================
# The `random` provider generates a random string.
# We use this for the DB password so:
#   - It's never in your code
#   - It's never in your git history
#   - It's strong (16 chars, letters + numbers)
#
# special = false because some special chars cause issues
# with MySQL connection strings.
# ============================================================

resource "random_password" "db_password" {
  length  = 16
  special = false
  # Result looks like: "xK8mN2pQ4rT6vW9z"
  # Terraform stores this in terraform.tfstate
  # NEVER commit tfstate to git — it contains secrets
}


# ============================================================
# 2. SSM PARAMETER STORE
# ============================================================
# SSM Parameter Store is AWS's secret storage service.
# A "SecureString" parameter is encrypted at rest using KMS.
#
# When your app starts, it calls SSM to get the password.
# The EC2 IAM role has permission to do this call.
# The password is never stored in environment variables
# or config files on disk.
#
# Path convention: /appname/component/secret
# Using paths like /myapp/* makes IAM policy scoping easy.
# ============================================================

resource "aws_ssm_parameter" "db_password" {
  name        = "/myapp/db/password"
  description = "RDS MySQL master password"
  type        = "SecureString" # Encrypted with KMS
  value       = random_password.db_password.result
  key_id      = aws_kms_key.main.arn # Use our CMK, not AWS-managed key

  tags = {
    Name = "db-password"
  }
}

resource "aws_ssm_parameter" "db_host" {
  name        = "/myapp/db/host"
  description = "RDS endpoint hostname"
  type        = "String" # Not sensitive — just a hostname
  value       = aws_db_instance.main.address
  # This creates a circular dependency issue:
  # RDS needs to exist before we can store its address.
  # Terraform resolves this automatically by building
  # a dependency graph. It creates RDS first, then SSM.
}

resource "aws_ssm_parameter" "db_name" {
  name  = "/myapp/db/name"
  type  = "String"
  value = var.db_name
}

resource "aws_ssm_parameter" "db_username" {
  name  = "/myapp/db/username"
  type  = "String"
  value = var.db_username
}


# ============================================================
# 3. RDS DB SUBNET GROUP
# ============================================================
# Before creating an RDS instance, you must create a
# "DB Subnet Group" — a collection of subnets where RDS
# is allowed to place itself.
#
# AWS requires at minimum 2 subnets in 2 different AZs.
# This is true even for Single-AZ deployments.
# It's an AWS requirement, not optional.
# ============================================================

resource "aws_db_subnet_group" "main" {
  name        = "main-db-subnet-group${var.suffix}"
  description = "Subnet group for RDS in private subnets"
  subnet_ids  = [
    aws_subnet.private_a.id,
    aws_subnet.private_b.id
    # Two private subnets, two AZs — meets AWS minimum requirement
  ]

  tags = {
    Name = "main-db-subnet-group${var.suffix}"
  }
}


# ============================================================
# 4. RDS MYSQL INSTANCE
# ============================================================
# This is the actual database. Key settings explained below.
#
# FREE TIER: db.t3.micro + 20GB gp2 + single AZ
# is covered under AWS Free Tier for 12 months.
# ============================================================

resource "aws_db_instance" "main" {
  # --- Identity ---
  identifier = "secure-3tier-db${var.suffix}" # Name shown in AWS console
  db_name    = var.db_name        # The database to create inside MySQL

  # --- Engine ---
  engine         = "mysql"
  engine_version = "8.0"

  # --- Size (Free Tier) ---
  instance_class    = var.db_instance_class # db.t3.micro
  allocated_storage = 20                    # GB — free tier limit is 20GB
  storage_type      = "gp2"                 # General purpose SSD

  # --- Credentials ---
  username = var.db_username
  password = random_password.db_password.result
  # Password comes from random_password resource above

  # --- Network ---
  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.db.id]
  publicly_accessible    = false # CRITICAL: DB is not internet-facing

  # --- Availability ---
  multi_az = false # Single-AZ for free tier
  # In production: multi_az = true
  # This creates a standby in another AZ for automatic failover

  # --- Security ---
  storage_encrypted = true
  # Uses AWS managed key (free) — to use our CMK instead:
  # kms_key_id = aws_kms_key.main.arn
  # (AWS managed key is fine for dev/free tier)

  # --- Backups ---
  backup_retention_period = 1   # Keep 7 days of automated backups
  backup_window           = "03:00-04:00" # UTC — when backups run
  maintenance_window      = "Mon:04:00-Mon:05:00"

  # --- Deletion Protection ---
  deletion_protection       = false # Set to true in production!
  skip_final_snapshot       = true  # Don't create a snapshot when we destroy
  # In production: skip_final_snapshot = false
  # So you have a backup before destroying the DB

  tags = {
    Name = "secure-3tier-mysql${var.suffix}"
  }
}
